### ISSUE TITLE
DEIMOS for Gaussian initializations

### ISSUE THREAD

**Issue by pmelchior** [pmelchior/scarlet2#48]
The Gaussian morphology inits from #47 amount to determine the moments of the observed image distribution. That means the forward pass will convolved them with the PSF again. It would be better if we could initialize them at their preconvolved values. And it turns out this can be done (as I derived [here](https://doi.org/10.1111/j.1365-2966.2010.17875.x)). There's an analytic mapping between the moments of the convolved $\lbrace G^\star \rbrace$, the deconvolved $\lbrace G \rbrace$, and the PSF moments $\lbrace P \rbrace$, which I conveniently summarized in Table 1:

<img width="807" alt="Screenshot 2024-04-05 at 16 26 57" src="https://github.com/pmelchior/scarlet2/assets/1463403/6d705fa7-63b9-4321-a9ab-edaf6c17e037">

In this the moments are defined as $\lbrace I \rbrace_{i,j} = \int d^2x I(x)x_1^i x_2^j$. So, these equations can be directly inverted analytically. Even better, I coded up the entire shebang in C++ _a long time ago_:
https://github.com/pmelchior/shapelens/blob/32393c390c8f8dada5448f120fbcd6d8ecb74e84/src/DEIMOS.cc#L89-L126

So, we should port this to python and add it to the `measure` module that will be brought from scarlet1 as part of #47.

**Comment by arunkannawadi** [comment]
I coded this up in Python a few years ago and would be happy to upstream it here from https://github.com/arunkannawadi/deimos/blob/master/deimos.py

**Comment by pmelchior** [comment]
Thanks, Arun. Matt has already copied my C++ code here: https://github.com/pmelchior/scarlet2/pull/47/files#diff-a1637f4d5cd86bd6354e3b353be9295d36b9a02b172bab1aea5d34e8a25fae4eR194
