### ISSUE TITLE
Sampler can no longer sample over point source center

### ISSUE THREAD

**Issue by charlotteaward** [pmelchior/scarlet2#57]
The sampler currently always has a runtime error if you sample over the morphology.center parameter for a point source (see error message below). If I run the sampler with the same setup but while keeping the morphology.center fixed and sampling over another parameter, it has no issues and proceeds normally. The center values coming from `dist.Normal(scene_.sources[indtransient].morphology.center, 0.01)` are all reasonable. 

This error arises even when there are no constraints applied to any source parameters, on images with real or Null WCS's, and on simulated and real data. 

```
RuntimeError                              Traceback (most recent call last)
Cell In[21], line 6
      4 print(scene_.sources[indtransient].morphology.center)
      5 scene_.set_info('sources.'+str(indtransient)+'.morphology.center', fixed=False, prior=dist.Normal(scene_.sources[indtransient].morphology.center, 0.01))
----> 6 mcmc = scene_.sample(observations_sc2,num_warmup=100, num_samples=300) 
      7 q = mcmc.get_samples()['sources.'+str(indtransient)+'.morphology.center'] 
      8 q1 = np.percentile(q,[2.5,16,50,84,97.5],axis=0) 

File ~/scarletmultisource/scarlet2/scarlet2/scene.py:111, in Scene.sample(self, observations, num_warmup, num_samples, **kwargs)
    109 mcmc = MCMC(nuts_kernel, num_warmup=num_warmup, num_samples=num_samples)
    110 rng_key = jax.random.PRNGKey(0)
--> 111 mcmc.run(rng_key, self, obs=observations)
    112 return mcmc

File ~/.conda/envs/scarlet/lib/python3.10/site-packages/numpyro/infer/mcmc.py:628, in MCMC.run(self, rng_key, extra_fields, init_params, *args, **kwargs)
    626 map_args = (rng_key, init_state, init_params)
    627 if self.num_chains == 1:
--> 628     states_flat, last_state = partial_map_fn(map_args)
    629     states = tree_map(lambda x: x[jnp.newaxis, ...], states_flat)
    630 else:

File ~/.conda/envs/scarlet/lib/python3.10/site-packages/numpyro/infer/mcmc.py:410, in MCMC._single_chain_mcmc(self, init, args, kwargs, collect_fields)
    408 # Check if _sample_fn is None, then we need to initialize the sampler.
    409 if init_state is None or (getattr(self.sampler, "_sample_fn", None) is None):
--> 410     new_init_state = self.sampler.init(
    411         rng_key,
    412         self.num_warmup,
    413         init_params,
    414         model_args=args,
    415         model_kwargs=kwargs,
    416     )
    417     init_state = new_init_state if init_state is None else init_state
    418 sample_fn, postprocess_fn = self._get_cached_fns()

File ~/.conda/envs/scarlet/lib/python3.10/site-packages/numpyro/infer/hmc.py:713, in HMC.init(self, rng_key, num_warmup, init_params, model_args, model_kwargs)
    708 # vectorized
    709 else:
    710     rng_key, rng_key_init_model = jnp.swapaxes(
    711         vmap(random.split)(rng_key), 0, 1
    712     )
--> 713 init_params = self._init_state(
    714     rng_key_init_model, model_args, model_kwargs, init_params
    715 )
    716 if self._potential_fn and init_params is None:
    717     raise ValueError(
    718         "Valid value of `init_params` must be provided with" " `potential_fn`."
    719     )

File ~/.conda/envs/scarlet/lib/python3.10/site-packages/numpyro/infer/hmc.py:657, in HMC._init_state(self, rng_key, model_args, model_kwargs, init_params)
    650 def _init_state(self, rng_key, model_args, model_kwargs, init_params):
    651     if self._model is not None:
    652         (
    653             new_init_params,
    654             potential_fn,
    655             postprocess_fn,
    656             model_trace,
--> 657         ) = initialize_model(
    658             rng_key,
    659             self._model,
    660             dynamic_args=True,
    661             init_strategy=self._init_strategy,
    662             model_args=model_args,
    663             model_kwargs=model_kwargs,
    664             forward_mode_differentiation=self._forward_mode_differentiation,
    665         )
    666         if init_params is None:
    667             init_params = new_init_params

File ~/.conda/envs/scarlet/lib/python3.10/site-packages/numpyro/infer/util.py:745, in initialize_model(rng_key, model, init_strategy, dynamic_args, model_args, model_kwargs, forward_mode_differentiation, validate_grad)
    732                             w.message.args = (
    733                                 "Site {}: {}".format(
    734                                     site["name"], w.message.args[0]
    735                                 ),
    736                             ) + w.message.args[1:]
    737                             warnings.showwarning(
    738                                 w.message,
    739                                 w.category,
   (...)
    743                                 line=w.line,
    744                             )
--> 745         raise RuntimeError(
    746             "Cannot find valid initial parameters. Please check your model again."
    747         )
    748 return ModelInfo(
    749     ParamInfo(init_params, pe, grad), potential_fn, postprocess_fn, model_trace
    750 )

RuntimeError: Cannot find valid initial parameters. Please check your model again.
```

**Comment by pmelchior** [comment]
We may have broken the sampler because it wasn't tested automatically (yes, we should have a barebones test script...).

What makes you think that it's the commit you liked above?

**Comment by charlotteaward** [comment]
Since there aren't any user-added constraints in my test cases to violate when checking parameter validity, I was looking for changes that would affect how PointSource parameters are checked and therefore cause a bug. This was the only thing I noticed that might be related, since Sources are now made up of Components, but I can't really see how it would cause an in issue, since I can sample over the PointSource spectrum just fine. 

I'm pretty stuck over how to debug this since the initial parameter state checks are happening in numpyro, and the inputs seem fine. Is it possible that the sampler is interpreting coordinates differently to scene.sample?

**Comment by pmelchior** [comment]
Are there any other parameters in the scene that you want to sample from? I wonder whether this is related to the point source center at all.

**Comment by charlotteaward** [comment]
Not in this particular case, but I can sample over other parameters (e.g. Point Source spectrum, or adjacent galaxy spectrum) with no problem if I free up those parameters instead. It only gives the error when the point source center parameter is unfixed.

**Comment by charlotteaward** [comment]
Example script (for the simulated data) and the required fits files uploaded to this repo: https://github.com/charlotteaward/TimeDomainScarlet2 Cell 17 is where the problem is.

**Comment by pmelchior** [comment]
OK, thanks. I don't see an obvious problem, but I wonder if the previous fit actually optimized the center of the transient source at all. The fitter runs, but you only show the flux at the end of cell 15. So, I wonder if the error in cell 17 is triggered by having _no_ free parameter to work with. In essence, I'm not sure if the string `'sources.'+str(indtransient)+'.morphology.center'` resolves to the piece of the model you want to optimize.

**Comment by charlotteaward** [comment]
@pmelchior Just checked and the value of `scene.sources[indtransient].morphology.center` changes from [29.46838  29.522345] to [29.436949 29.478968] when unfixed the same way before running scene.fit, so I think it's resolving correctly. And the error in cell 17 is triggered regardless of whether it's just the point source center I try to sample over, or both the point source center and point source spectrum. If I fix the point source center it samples the spectrum just fine. My impression is that something about the validity checking is going wrong for this kind of point source center parameter, for some reason.
