### ISSUE TITLE
port initialization routines from scarlet1

### ISSUE THREAD

**Issue by pmelchior** [pmelchior/scarlet2#8]
scarlet1 has very well designed initializations, which we should port as much as possible. In scarlet1, we assumed we took control of the entire source creation and initialized all of its parameters. But the approach of specifying sources is different in scarlet2, where all parameters are exposed to the user:
```python
Source(
        center,
        ArraySpectrum(Parameter(spectrum, constraint=constraints.positive, stepsize=1)),
        ArrayMorphology(Parameter(morph, constraint=constraints.positive, stepsize=1e-1))
    )
```
We could extend it to something very modular like (following flax/stax style of initialization):
```python
def init_spectrum(obs, center):
    return obs.data[center]

Source(
        center,
        ArraySpectrum(Parameter(None, constraint=constraints.positive, stepsize=1, init_fn=init_spectrum)),
        ArrayMorphology(Parameter(morph, constraint=constraints.positive, stepsize=1e-1))
    )
```
but then `init_spectrum` would need to know how to get `obs`, and `center`. Much more transparent to the user and enabled by the state-preserving `equinox` is something like this:
```python
spectrum = init_spectrum(obs, center)
Source(
        center,
        ArraySpectrum(Parameter(spectrum, constraint=constraints.positive, stepsize=1)),
        ArrayMorphology(Parameter(morph, constraint=constraints.positive, stepsize=1e-1))
    )
```
For the morphology, we would do the same, with the main problem that we don't have a port of the monotonicity operator from scarlet1 (yet). I think we could port if it we don't require it to be jitable.

**Comment by SampsonML** [comment]
Working on this slowly, and naively here (https://github.com/pmelchior/scarlet2/blob/initializations/scarlet2/initialization.py)

**Comment by pmelchior** [comment]
Can we close this in favor of #33 ?

**Comment by pmelchior** [comment]
@SampsonML can we close this issue in favor of #33?

**Comment by SampsonML** [comment]
Discussion moved to #47
