### ISSUE TITLE
Missing attribute 'make_parameters'

### ISSUE THREAD

**Issue by qifengcheng** [pmelchior/scarlet2#84]
Hi I run into this error when running the notebook `Simulated_SN_example`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[56], line 70
     68 stepbig = lambda p: scarlet2.relative_step(p, factor=1e-3)
     69 stepverysmall = lambda p: scarlet2.relative_step(p, factor=2e-5)
---> 70 parameters = scene.make_parameters()
     71 for i in range(len(scene.sources)):
     72     if i==indtransient:

AttributeError: 'Scene' object has no attribute 'make_parameters'

**Comment by pmelchior** [comment]
How did you install scarlet2? If it's pip, what's the version? If it's from github, what's the git hash of the latest commit?

**Comment by qifengcheng** [comment]
Hi I installed with pip, with version: 0.1.0

**Comment by pmelchior** [comment]
Ah, I see. This is a very old version, but I hadn't updated it since. However, I just made the current development version available with pip as version 0.2.0. Please update and confirm that the problem disappears.

**Comment by qifengcheng** [comment]
Yes that works now. Thank you!
